document.getElementById("boton1").onclick = function(){
  var body1 = document.getElementById('body');
  var div1 = document.getElementById('div1');
  var div2 = document.getElementById('div2');
  var div3 = document.getElementById('div3');
  var div4 = document.getElementById('div4');
  var h21 = document.getElementById('h2');
  var button1 = document.getElementById('boton1');
  var button2 = document.getElementById('boton2');
  var button3 = document.getElementById('boton3');
  body1.style.fontFamily = "Verdana, Geneva, Tahoma, sans-serif"
  body1.style.textAlign = "justify"
  body.style.backgroundColor = "white"
  h21.style.backgroundColor = "antiquewhite"
  div1.style.backgroundColor = "antiquewhite"
  div2.style.backgroundColor = "antiquewhite"
  div3.style.backgroundColor = "antiquewhite"
  div4.style.backgroundColor = "antiquewhite" 
  button1.style.backgroundColor = "#ee9c9c"
  button2.style.backgroundColor = "#ee9c9c"
  button3.style.backgroundColor = "#ee9c9c"
  button1.style.borderRadius = "50%"
  button2.style.borderRadius = "50%"
  button3.style.borderRadius = "50%"
}

document.getElementById('boton2').onclick = function(){
  var h21 = document.getElementById("h2")
  var button1 = document.getElementById('boton1');
  var button2 = document.getElementById('boton2');
  var button3 = document.getElementById('boton3');
  var div1 = document.getElementById("div1");
  var div2 = document.getElementById("div2");
  var div3 = document.getElementById("div3");
  var div4 = document.getElementById("div4");
  body.style.backgroundColor = "white"
  h21.style.padding = "5xp"
  h21.style.backgroundColor = "white"
  button1.style.backgroundColor = "#7b6e5c"
  button2.style.backgroundColor = "#94784d"
  button3.style.backgroundColor = "#f5cb98"
  button1.style.borderRadius = "20%"
  button2.style.borderRadius = "30%"
  button3.style.borderRadius = "40%"
  div1.style.fontFamily = "Arial, Helvetica, sans-serif"
  div1.style.backgroundColor = "aliceblue"
  div1.style.textAlign = "justify"
  div1.style.fontSize = "large"
  div1.style.left = "5%"
  div1.style.width = "90%"
  div2.style.fontFamily = "cursive"
  div2.style.backgroundColor = "antiquewhite"
  div2.style.textAlign = "center"
  div2.style.width = "80%"
  div2.style.left = "10%"
  div3.style.fontFamily = "Verdana, Geneva, Tahoma, sans-serif0"
  div3.style.backgroundColor = "beige"
  div3.style.fontSize = "small"
  div3.style.left = "10px"
  div4.style.fontFamily = "Georgia, 'Times New Roman', Times, serif"
  div4.style.backgroundColor = "burlywood"
  div4.style.textAlign = "center"
}

document.getElementById('boton3').onclick = function(){
  var h21 = document.getElementById("h2")
  var button1 = document.getElementById('boton1');
  var button2 = document.getElementById('boton2');
  var button3 = document.getElementById('boton3');
  var div1 = document.getElementById("div1");
  var div2 = document.getElementById("div2");
  var div3 = document.getElementById("div3");
  var div4 = document.getElementById("div4");
  var body = document.getElementById("body");
  body.style.backgroundColor = "#ffebcd"
  h21.style.width = "80%"
  h21.style.backgroundColor = "cyan"
  h21.style.left = "37%"
  button1.style.backgroundColor = "aquamarine"
  button2.style.backgroundColor = "aquamarine"
  button3.style.backgroundColor = "aquamarine"
  div1.style.backgroundColor = "darkseagreen"
  div1.style.textAlign = "center"
  div1.style.fontFamily = "'Segoe UI', Tahoma, Geneva, Verdana, sans-serif"
  div2.style.backgroundColor = "darkseagreen"
  div2.style.textAlign = "center"
  div2.style.fontFamily = "'Segoe UI', Tahoma, Geneva, Verdana, sans-serif"
  div3.style.backgroundColor = "darkturquoise"
  div3.style.textAlign = "justify"
  div3.style.fontFamily = "cursive"
  div4.style.backgroundColor = "darkturquoise"
  div4.style.textAlign = "justify"
  div4.style.fontFamily = "cursive"
}